name: Sync Fork

on:
  # schedule:
  #   - cron: '*/30 * * * *' # every 30 minutes
  workflow_dispatch: # on button click

jobs:
  list:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.get_repos.outputs.result }}
    steps:
      - uses: actions/github-script@v7
        id: get_repos
        with:
          script: |
            const res = await github.rest.repos.listForOrg({
              context.repo.owner,
            })
            const repos = res.data
            return repos.filter(repo => {
              if (repo.fork) {
                return {
                  name: repo.name,
                  parent: repo.parent,
                  default_branch: repo.default_branch
                }
              }
            })
  sync:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo: ${{ needs.list.outputs.matrix }}
    steps:
      - uses: tgymnich/fork-sync@v1.8
        with:
          owner: ${{ matrix.repo.parent }}
          base: ${{ matrix.repo.default_branch }}
          head: ${{ matrix.repo.default_branch }}
