name: Check Patterns

permissions:
  contents: read
  pull-requests: read

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  check-patterns:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install dependencies
        run: npm install

      - name: Compile TypeScript
        run: npm run build

      - name: Run check-patterns script
        run: node lib/index.js
