# Workflow for enforcing Open Source Security Policy

name: Open Source Security Policy Enforcement

permissions:
  contents: read
  pull-requests: read

on: [pull_request, pull_request_target]

jobs:
  trufflehog:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Secret Scanning
      uses: trufflesecurity/trufflehog@main
      with:
        extra_args: --results=verified,unknown
